server:
    port: ${PORT:8888}
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:  # 配置git
                    uri: https://gitee.com/smiledouble/java0817-ego-shop-config.git
                    username: smiledouble
                    password: cxs1013..
                    search-paths: /ego-shop-config/**
            discovery:
                enabled: true  # 开启配置文件发现功能
    rabbitmq:  # mq的配置
        host: 192.168.127.128
        port: 5672
        username: whsxt
        password: whsxt
        virtual-host: /v-whsxt
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER:http://admin:admin@localhost:8761/eureka}
    instance:
        hostname: ${HOST:localhost}
        prefer-ip-address: true
        instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
        lease-renewal-interval-in-seconds: 3
        lease-expiration-duration-in-seconds: 9
management:
    endpoints:
        web:
            exposure:
                include: '*'